---
application:
  name: "fb-api"
  project: "message"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "db_fb_api"
  version: "8.0"
routers:
- name: "main-fb-api"
  routes:
  - application_name: "fb-api"
    paths:
    - "/*"
